name: dotnet-ecommerce-microservice

services:
  mongodb-container:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ../mongo-init:/docker-entrypoint-initdb.d
    networks:
      - orders-microservice-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ordersservice.api:
    image: ordersserviceapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: OrdersService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=${ORDERS_DB_CONNECTION_STRING}
      - UsersMicroserviceName=${USERS_MICROSERVICE_NAME}
      - UsersMicroservicePort=${USERS_MICROSERVICE_PORT}
      - ProductsMicroserviceName=${PRODUCTS_MICROSERVICE_NAME}
      - ProductsMicroservicePort=${PRODUCTS_MICROSERVICE_PORT}
      - MongoDBDatabaseName=${MONGODB_DATABASE_NAME}
      - Redis_Host=${REDIS_HOST}
      - Redis_Port=${REDIS_PORT}
      - RabbitMQ_HostName=${RABBITMQ_HOSTNAME}
      - RabbitMQ_UserName=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ_Password=${RABBITMQ_DEFAULT_PASS}
      - RabbitMQ_Port=${RABBITMQ_PORT}
      - RabbitMQ_Products_Exchange_Name=${RABBITMQ_PRODUCTS_EXCHANGE_NAME}
    env_file:
      - .env
    ports:
      - "7000:8080"
    depends_on:
      mongodb-container:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce-network
      - orders-microservice-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  mysql-container:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${PRODUCTS_DATABASE_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ../mysql-init:/docker-entrypoint-initdb.d
    networks:
      - products-microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  products-microservice:
    image: productsserviceapi
    restart: unless-stopped
    build:
      context: ../eCommerceSolution.ProductsService
      dockerfile: ProductsService.API/Dockerfile
    ports:
      - "6000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${PRODUCTS_DB_CONNECTION_STRING}
      - RabbitMQ_HostName=${RABBITMQ_HOSTNAME}
      - RabbitMQ_UserName=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ_Password=${RABBITMQ_DEFAULT_PASS}
      - RabbitMQ_Port=${RABBITMQ_PORT}
      - RabbitMQ_Products_Exchange_Name=${RABBITMQ_PRODUCTS_EXCHANGE_NAME}
    env_file:
      - .env
    depends_on:
      mysql-container:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-network
      - products-microservice-network

  postgres-container:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${USERS_DATABASE_ROOT_PASSWORD}
      # this line creates the database automatically when the container starts, using the value from the .env file
      - POSTGRES_DB=${USERS_DATABASE}
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ../postgres-init:/docker-entrypoint-initdb.d
    networks:
      - users-microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  users-microservice:
    image: usersserviceapi
    restart: unless-stopped
    build:
      context: ../eCommerceSolution.UsersService
      dockerfile: eCommerce.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=${USERS_DB_CONNECTION_STRING}
    env_file:
      - .env
    depends_on:
      postgres-container:
        condition: service_healthy
    networks:
      - ecommerce-network
      - users-microservice-network

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/Jaccey/Desktop/csharp/eCommerce/redis-cache:/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  apigateway:
    image: apigateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    depends_on:
      ordersservice.api:
        condition: service_started
      products-microservice:
        condition: service_started
      users-microservice:
        condition: service_started
    ports:
      - "4000:8080"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

networks:
  ecommerce-network:
    driver: bridge
  products-microservice-network:
    driver: bridge
  users-microservice-network:
    driver: bridge
  orders-microservice-network:
    driver: bridge
